#include "ida_stm32f10x_vector.h"

vector_t stm32f10x_common_vectors[STM32F10X_COMMON_IRQ_COUNT] =
{
  {"WWDG_vect", "WWDG_IRQHandler", "Window WatchDog Interrupt"},
  {"PVD_vect", "PVD_IRQHandler", "PVD through EXTI Line detection Interrupt"},
  {"TAMPER_vect", "TAMPER_IRQHandler", "Tamper Interrupt"},
  {"RTC_vect", "RTC_IRQHandler", "RTC global Interrupt"},
  {"FLASH_vect", "FLASH_IRQHandler", "FLASH global Interrupt"},
  {"RCC_vect", "RCC_IRQHandler", "RCC global Interrupt"},
  {"EXTI0_vect", "EXTI0_IRQHandler", "EXTI Line0 Interrupt"},
  {"EXTI1_vect", "EXTI1_IRQHandler", "EXTI Line1 Interrupt"},
  {"EXTI2_vect", "EXTI2_IRQHandler", "EXTI Line2 Interrupt"},
  {"EXTI3_vect", "EXTI3_IRQHandler", "EXTI Line3 Interrupt"},
  {"EXTI4_vect", "EXTI4_IRQHandler", "EXTI Line4 Interrupt"},
  {"DMA1_Channel1_vect", "DMA1_Channel1_IRQHandler", "DMA1 Channel 1 global Interrupt"},
  {"DMA1_Channel2_vect", "DMA1_Channel2_IRQHandler", "DMA1 Channel 2 global Interrupt"},
  {"DMA1_Channel3_vect", "DMA1_Channel3_IRQHandler", "DMA1 Channel 3 global Interrupt"},
  {"DMA1_Channel4_vect", "DMA1_Channel4_IRQHandler", "DMA1 Channel 4 global Interrupt"},
  {"DMA1_Channel5_vect", "DMA1_Channel5_IRQHandler", "DMA1 Channel 5 global Interrupt"},
  {"DMA1_Channel6_vect", "DMA1_Channel6_IRQHandler", "DMA1 Channel 6 global Interrupt"},
  {"DMA1_Channel7_vect", "DMA1_Channel7_IRQHandler", "DMA1 Channel 7 global Interrupt"},
};

vector_t stm32f10x_ld_vl_vectors[STM32F10X_LD_VL_IRQ_COUNT] =
{
  {"ADC1_vect", "ADC1_IRQHandler", "ADC1 global Interrupt"},
  {"Reserved0",  NULL, "Reserved"},
  {"Reserved1",  NULL, "Reserved"},
  {"Reserved2",  NULL, "Reserved"},
  {"Reserved3",  NULL, "Reserved"},
  {"EXTI9_5_vect", "EXTI9_5_IRQHandler", "External Line[9:5] Interrupts"},
  {"TIM1_BRK_TIM15_vect", "TIM1_BRK_TIM15_IRQHandler", "TIM1 Break and TIM15 Interrupts"},
  {"TIM1_UP_TIM16_vect", "TIM1_UP_TIM16_IRQHandler", "TIM1 Update and TIM16 Interrupts"},
  {"TIM1_TRG_COM_TIM17_vect", "TIM1_TRG_COM_TIM17_IRQHandler", "TIM1 Trigger and Commutation and TIM17 Interrupt"},
  {"TIM1_CC_vect", "TIM1_CC_IRQHandler", "TIM1 Capture Compare Interrupt"},
  {"TIM2_vect", "TIM2_IRQHandler", "TIM2 global Interrupt"},
  {"TIM3_vect", "TIM3_IRQHandler", "TIM3 global Interrupt"},
  {"Reserved4",  NULL, "Reserved"},
  {"I2C1_EV_vect", "I2C1_EV_IRQHandler", "I2C1 Event Interrupt"},
  {"I2C1_ER_vect", "I2C1_ER_IRQHandler", "I2C1 Error Interrupt"},
  {"Reserved5",  NULL, "Reserved"},
  {"Reserved6",  NULL, "Reserved"},
  {"SPI1_vect", "SPI1_IRQHandler", "SPI1 global Interrupt"},
  {"Reserved7",  NULL, "Reserved"},
  {"USART1_vect", "USART1_IRQHandler", "USART1 global Interrupt"},
  {"USART2_vect", "USART2_IRQHandler", "USART2 global Interrupt"},
  {"Reserved8",  NULL, "Reserved"},
  {"EXTI15_10_vect", "EXTI15_10_IRQHandler", "External Line[15:10] Interrupts"},
  {"RTCAlarm_vect", "RTCAlarm_IRQHandler", "RTC Alarm through EXTI Line Interrupt"},
  {"CEC_vect", "CEC_IRQHandler", "HDMI-CEC Interrupt"},
  {"Reserved9",  NULL, "Reserved"},
  {"ReservedA",  NULL, "Reserved"},
  {"ReservedB",  NULL, "Reserved"},
  {"ReservedC",  NULL, "Reserved"},
  {"ReservedD",  NULL, "Reserved"},
  {"ReservedE",  NULL, "Reserved"},
  {"ReservedF",  NULL, "Reserved"},
  {"ReservedG",  NULL, "Reserved"},
  {"ReservedH",  NULL, "Reserved"},
  {"ReservedI",  NULL, "Reserved"},
  {"ReservedJ",  NULL, "Reserved"},
  {"TIM6_DAC_vect", "TIM6_DAC_IRQHandler", "TIM6 and DAC underrun Interrupt"},
  {"TIM7_vect", "TIM7_IRQHandler", "TIM7 Interrupt"},
};

vector_t stm32f10x_md_vl_vectors[STM32F10X_MD_VL_IRQ_COUNT] =
{
  {"ADC1_vect", "ADC1_IRQHandler", "ADC1 global Interrupt"},
  {"Reserved0",  NULL, "Reserved"},
  {"Reserved1",  NULL, "Reserved"},
  {"Reserved2",  NULL, "Reserved"},
  {"Reserved3",  NULL, "Reserved"},
  {"EXTI9_5_vect", "EXTI9_5_IRQHandler", "External Line[9:5] Interrupts"},
  {"TIM1_BRK_TIM15_vect", "TIM1_BRK_TIM15_IRQHandler", "TIM1 Break and TIM15 Interrupts"},
  {"TIM1_UP_TIM16_vect", "TIM1_UP_TIM16_IRQHandler", "TIM1 Update and TIM16 Interrupts"},
  {"TIM1_TRG_COM_TIM17_vect", "TIM1_TRG_COM_TIM17_IRQHandler", "TIM1 Trigger and Commutation and TIM17 Interrupt"},
  {"TIM1_CC_vect", "TIM1_CC_IRQHandler", "TIM1 Capture Compare Interrupt"},
  {"TIM2_vect", "TIM2_IRQHandler", "TIM2 global Interrupt"},
  {"TIM3_vect", "TIM3_IRQHandler", "TIM3 global Interrupt"},
  {"TIM4_vect", "TIM4_IRQHandler", "TIM4 global Interrupt"},
  {"I2C1_EV_vect", "I2C1_EV_IRQHandler", "I2C1 Event Interrupt"},
  {"I2C1_ER_vect", "I2C1_ER_IRQHandler", "I2C1 Error Interrupt"},
  {"I2C2_EV_vect", "I2C2_EV_IRQHandler", "I2C2 Event Interrupt"},
  {"I2C2_ER_vect", "I2C2_ER_IRQHandler", "I2C2 Error Interrupt"},
  {"SPI1_vect", "SPI1_IRQHandler", "SPI1 global Interrupt"},
  {"SPI2_vect", "SPI2_IRQHandler", "SPI2 global Interrupt"},
  {"USART1_vect", "USART1_IRQHandler", "USART1 global Interrupt"},
  {"USART2_vect", "USART2_IRQHandler", "USART2 global Interrupt"},
  {"USART3_vect", "USART3_IRQHandler", "USART3 global Interrupt"},
  {"EXTI15_10_vect", "EXTI15_10_IRQHandler", "External Line[15:10] Interrupts"},
  {"RTCAlarm_vect", "RTCAlarm_IRQHandler", "RTC Alarm through EXTI Line Interrupt"},
  {"CEC_vect", "CEC_IRQHandler", "HDMI-CEC Interrupt"},
  {"Reserved4",  NULL, "Reserved"},
  {"Reserved5",  NULL, "Reserved"},
  {"Reserved6",  NULL, "Reserved"},
  {"Reserved7",  NULL, "Reserved"},
  {"Reserved8",  NULL, "Reserved"},
  {"Reserved9",  NULL, "Reserved"},
  {"ReservedA",  NULL, "Reserved"},
  {"ReservedB",  NULL, "Reserved"},
  {"ReservedC",  NULL, "Reserved"},
  {"ReservedD",  NULL, "Reserved"},
  {"ReservedE",  NULL, "Reserved"},
  {"TIM6_DAC_vect", "TIM6_DAC_IRQHandler", "TIM6 and DAC underrun Interrupt"},
  {"TIM7_vect", "TIM7_IRQHandler", "TIM7 Interrupt"},
};

vector_t stm32f10x_hd_vl_vectors[STM32F10X_HD_VL_IRQ_COUNT] =
{
  {"ADC1_vect", "ADC1_IRQHandler", "ADC1 global Interrupt"},
  {"Reserved0",  NULL, "Reserved"},
  {"Reserved1",  NULL, "Reserved"},
  {"Reserved2",  NULL, "Reserved"},
  {"Reserved3",  NULL, "Reserved"},
  {"EXTI9_5_vect", "EXTI9_5_IRQHandler", "External Line[9:5] Interrupts"},
  {"TIM1_BRK_TIM15_vect", "TIM1_BRK_TIM15_IRQHandler", "TIM1 Break and TIM15 Interrupts"},
  {"TIM1_UP_TIM16_vect", "TIM1_UP_TIM16_IRQHandler", "TIM1 Update and TIM16 Interrupts"},
  {"TIM1_TRG_COM_TIM17_vect", "TIM1_TRG_COM_TIM17_IRQHandler", "TIM1 Trigger and Commutation and TIM17 Interrupt"},
  {"TIM1_CC_vect", "TIM1_CC_IRQHandler", "TIM1 Capture Compare Interrupt"},
  {"TIM2_vect", "TIM2_IRQHandler", "TIM2 global Interrupt"},
  {"TIM3_vect", "TIM3_IRQHandler", "TIM3 global Interrupt"},
  {"TIM4_vect", "TIM4_IRQHandler", "TIM4 global Interrupt"},
  {"I2C1_EV_vect", "I2C1_EV_IRQHandler", "I2C1 Event Interrupt"},
  {"I2C1_ER_vect", "I2C1_ER_IRQHandler", "I2C1 Error Interrupt"},
  {"I2C2_EV_vect", "I2C2_EV_IRQHandler", "I2C2 Event Interrupt"},
  {"I2C2_ER_vect", "I2C2_ER_IRQHandler", "I2C2 Error Interrupt"},
  {"SPI1_vect", "SPI1_IRQHandler", "SPI1 global Interrupt"},
  {"SPI2_vect", "SPI2_IRQHandler", "SPI2 global Interrupt"},
  {"USART1_vect", "USART1_IRQHandler", "USART1 global Interrupt"},
  {"USART2_vect", "USART2_IRQHandler", "USART2 global Interrupt"},
  {"USART3_vect", "USART3_IRQHandler", "USART3 global Interrupt"},
  {"EXTI15_10_vect", "EXTI15_10_IRQHandler", "External Line[15:10] Interrupts"},
  {"RTCAlarm_vect", "RTCAlarm_IRQHandler", "RTC Alarm through EXTI Line Interrupt"},
  {"CEC_vect", "CEC_IRQHandler", "HDMI-CEC Interrupt"},
  {"TIM12_vect", "TIM12_IRQHandler", "TIM12 global Interrupt"},
  {"TIM13_vect", "TIM13_IRQHandler", "TIM13 global Interrupt"},
  {"TIM14_vect", "TIM14_IRQHandler", "TIM14 global Interrupt"},
  {"Reserved4",  NULL, "Reserved"},
  {"Reserved5",  NULL, "Reserved"},
  {"Reserved6",  NULL, "Reserved"},
  {"Reserved7",  NULL, "Reserved"},
  {"TIM5_vect", "TIM5_IRQHandler", "TIM5 global Interrupt"},
  {"SPI3_vect", "SPI3_IRQHandler", "SPI3 global Interrupt"},
  {"UART4_vect", "UART4_IRQHandler", "UART4 global Interrupt"},
  {"UART5_vect", "UART5_IRQHandler", "UART5 global Interrupt"},
  {"TIM6_DAC_vect", "TIM6_DAC_IRQHandler", "TIM6 and DAC underrun Interrupt"},
  {"TIM7_vect", "TIM7_IRQHandler", "TIM7 Interrupt"},
  {"DMA2_Channel1_vect", "DMA2_Channel1_IRQHandler", "DMA2 Channel 1 global Interrupt"},
  {"DMA2_Channel2_vect", "DMA2_Channel2_IRQHandler", "DMA2 Channel 2 global Interrupt"},
  {"DMA2_Channel3_vect", "DMA2_Channel3_IRQHandler", "DMA2 Channel 3 global Interrupt"},
  {"DMA2_Channel4_5_vect", "DMA2_Channel4_5_IRQHandler", "DMA2 Channel 4 and Channel 5 global Interrupt"},
  {"DMA2_Channel5_vect", "DMA2_Channel5_IRQHandler", "DMA2 Channel 5 global Interrupt"},
};


vector_t stm32f10x_ld_vectors[STM32F10X_LD_IRQ_COUNT] =
{
  {"ADC1_2_vect", "ADC1_2_IRQHandler", "ADC1 and ADC2 global Interrupt"},
  {"USB_HP_CAN1_TX_vect", "USB_HP_CAN1_TX_IRQHandler", "USB Device High Priority or CAN1 TX Interrupts"},
  {"USB_LP_CAN1_RX0_vect", "USB_LP_CAN1_RX0_IRQHandler", "USB Device Low Priority or CAN1 RX0 Interrupts"},
  {"CAN1_RX1_vect", "CAN1_RX1_IRQHandler", "CAN1 RX1 Interrupt"},
  {"CAN1_SCE_vect", "CAN1_SCE_IRQHandler", "CAN1 SCE Interrupt"},
  {"EXTI9_5_vect", "EXTI9_5_IRQHandler", "External Line[9:5] Interrupts"},
  {"TIM1_BRK_vect", "TIM1_BRK_IRQHandler", "TIM1 Break Interrupt"},
  {"TIM1_UP_vect", "TIM1_UP_IRQHandler", "TIM1 Update Interrupt"},
  {"TIM1_TRG_COM_vect", "TIM1_TRG_COM_IRQHandler", "TIM1 Trigger and Commutation Interrupt"},
  {"TIM1_CC_vect", "TIM1_CC_IRQHandler", "TIM1 Capture Compare Interrupt"},
  {"TIM2_vect", "TIM2_IRQHandler", "TIM2 global Interrupt"},
  {"TIM3_vect", "TIM3_IRQHandler", "TIM3 global Interrupt"},
  {"Reserved0",  NULL, "Reserved"},
  {"I2C1_EV_vect", "I2C1_EV_IRQHandler", "I2C1 Event Interrupt"},
  {"I2C1_ER_vect", "I2C1_ER_IRQHandler", "I2C1 Error Interrupt"},
  {"Reserved1",  NULL, "Reserved"},
  {"Reserved2",  NULL, "Reserved"},
  {"SPI1_vect", "SPI1_IRQHandler", "SPI1 global Interrupt"},
  {"Reserved3",  NULL, "Reserved"},
  {"USART1_vect", "USART1_IRQHandler", "USART1 global Interrupt"},
  {"USART2_vect", "USART2_IRQHandler", "USART2 global Interrupt"},
  {"Reserved4",  NULL, "Reserved"},
  {"EXTI15_10_vect", "EXTI15_10_IRQHandler", "External Line[15:10] Interrupts"},
  {"RTCAlarm_vect", "RTCAlarm_IRQHandler", "RTC Alarm through EXTI Line Interrupt"},
  {"USBWakeUp_vect", "USBWakeUp_IRQHandler", "USB Device WakeUp from suspend through EXTI Line Interrupt"},
};

vector_t stm32f10x_md_vectors[STM32F10X_MD_IRQ_COUNT] =
{
  {"ADC1_2_vect", "ADC1_2_IRQHandler", "ADC1 and ADC2 global Interrupt"},
  {"USB_HP_CAN1_TX_vect", "USB_HP_CAN1_TX_IRQHandler", "USB Device High Priority or CAN1 TX Interrupts"},
  {"USB_LP_CAN1_RX0_vect", "USB_LP_CAN1_RX0_IRQHandler", "USB Device Low Priority or CAN1 RX0 Interrupts"},
  {"CAN1_RX1_vect", "CAN1_RX1_IRQHandler", "CAN1 RX1 Interrupt"},
  {"CAN1_SCE_vect", "CAN1_SCE_IRQHandler", "CAN1 SCE Interrupt"},
  {"EXTI9_5_vect", "EXTI9_5_IRQHandler", "External Line[9:5] Interrupts"},
  {"TIM1_BRK_vect", "TIM1_BRK_IRQHandler", "TIM1 Break Interrupt"},
  {"TIM1_UP_vect", "TIM1_UP_IRQHandler", "TIM1 Update Interrupt"},
  {"TIM1_TRG_COM_vect", "TIM1_TRG_COM_IRQHandler", "TIM1 Trigger and Commutation Interrupt"},
  {"TIM1_CC_vect", "TIM1_CC_IRQHandler", "TIM1 Capture Compare Interrupt"},
  {"TIM2_vect", "TIM2_IRQHandler", "TIM2 global Interrupt"},
  {"TIM3_vect", "TIM3_IRQHandler", "TIM3 global Interrupt"},
  {"TIM4_vect", "TIM4_IRQHandler", "TIM4 global Interrupt"},
  {"I2C1_EV_vect", "I2C1_EV_IRQHandler", "I2C1 Event Interrupt"},
  {"I2C1_ER_vect", "I2C1_ER_IRQHandler", "I2C1 Error Interrupt"},
  {"I2C2_EV_vect", "I2C2_EV_IRQHandler", "I2C2 Event Interrupt"},
  {"I2C2_ER_vect", "I2C2_ER_IRQHandler", "I2C2 Error Interrupt"},
  {"SPI1_vect", "SPI1_IRQHandler", "SPI1 global Interrupt"},
  {"SPI2_vect", "SPI2_IRQHandler", "SPI2 global Interrupt"},
  {"USART1_vect", "USART1_IRQHandler", "USART1 global Interrupt"},
  {"USART2_vect", "USART2_IRQHandler", "USART2 global Interrupt"},
  {"USART3_vect", "USART3_IRQHandler", "USART3 global Interrupt"},
  {"EXTI15_10_vect", "EXTI15_10_IRQHandler", "External Line[15:10] Interrupts"},
  {"RTCAlarm_vect", "RTCAlarm_IRQHandler", "RTC Alarm through EXTI Line Interrupt"},
  {"USBWakeUp_vect", "USBWakeUp_IRQHandler", "USB Device WakeUp from suspend through EXTI Line Interrupt"},
};

vector_t stm32f10x_hd_vectors[STM32F10X_HD_IRQ_COUNT] =
{
  {"ADC1_2_vect", "ADC1_2_IRQHandler", "ADC1 and ADC2 global Interrupt"},
  {"USB_HP_CAN1_TX_vect", "USB_HP_CAN1_TX_IRQHandler", "USB Device High Priority or CAN1 TX Interrupts"},
  {"USB_LP_CAN1_RX0_vect", "USB_LP_CAN1_RX0_IRQHandler", "USB Device Low Priority or CAN1 RX0 Interrupts"},
  {"CAN1_RX1_vect", "CAN1_RX1_IRQHandler", "CAN1 RX1 Interrupt"},
  {"CAN1_SCE_vect", "CAN1_SCE_IRQHandler", "CAN1 SCE Interrupt"},
  {"EXTI9_5_vect", "EXTI9_5_IRQHandler", "External Line[9:5] Interrupts"},
  {"TIM1_BRK_vect", "TIM1_BRK_TIM9_IRQHandler", "TIM1 Break Interrupt"},
  {"TIM1_UP_vect", "TIM1_UP_TIM10_IRQHandler", "TIM1 Update Interrupt"},
  {"TIM1_TRG_COM_vect", "TIM1_TRG_COM_TIM11_IRQHandler", "TIM1 Trigger and Commutation Interrupt"},
  {"TIM1_CC_vect", "TIM1_CC_IRQHandler", "TIM1 Capture Compare Interrupt"},
  {"TIM2_vect", "TIM2_IRQHandler", "TIM2 global Interrupt"},
  {"TIM3_vect", "TIM3_IRQHandler", "TIM3 global Interrupt"},
  {"TIM4_vect", "TIM4_IRQHandler", "TIM4 global Interrupt"},
  {"I2C1_EV_vect", "I2C1_EV_IRQHandler", "I2C1 Event Interrupt"},
  {"I2C1_ER_vect", "I2C1_ER_IRQHandler", "I2C1 Error Interrupt"},
  {"I2C2_EV_vect", "I2C2_EV_IRQHandler", "I2C2 Event Interrupt"},
  {"I2C2_ER_vect", "I2C2_ER_IRQHandler", "I2C2 Error Interrupt"},
  {"SPI1_vect", "SPI1_IRQHandler", "SPI1 global Interrupt"},
  {"SPI2_vect", "SPI2_IRQHandler", "SPI2 global Interrupt"},
  {"USART1_vect", "USART1_IRQHandler", "USART1 global Interrupt"},
  {"USART2_vect", "USART2_IRQHandler", "USART2 global Interrupt"},
  {"USART3_vect", "USART3_IRQHandler", "USART3 global Interrupt"},
  {"EXTI15_10_vect", "EXTI15_10_IRQHandler", "External Line[15:10] Interrupts"},
  {"RTCAlarm_vect", "RTCAlarm_IRQHandler", "RTC Alarm through EXTI Line Interrupt"},
  {"USBWakeUp_vect", "USBWakeUp_IRQHandler", "USB Device WakeUp from suspend through EXTI Line Interrupt"},
  {"TIM8_BRK_vect", "TIM8_BRK_TIM12_IRQHandler", "TIM8 Break Interrupt"},
  {"TIM8_UP_vect", "TIM8_UP_TIM13_IRQHandler", "TIM8 Update Interrupt"},
  {"TIM8_TRG_COM_vect", "TIM8_TRG_COM_TIM14_IRQHandler", "TIM8 Trigger and Commutation Interrupt"},
  {"TIM8_CC_vect", "TIM8_CC_IRQHandler", "TIM8 Capture Compare Interrupt"},
  {"ADC3_vect", "ADC3_IRQHandler", "ADC3 global Interrupt"},
  {"FSMC_vect", "FSMC_IRQHandler", "FSMC global Interrupt"},
  {"SDIO_vect", "SDIO_IRQHandler", "SDIO global Interrupt"},
  {"TIM5_vect", "TIM5_IRQHandler", "TIM5 global Interrupt"},
  {"SPI3_vect", "SPI3_IRQHandler", "SPI3 global Interrupt"},
  {"UART4_vect", "UART4_IRQHandler", "UART4 global Interrupt"},
  {"UART5_vect", "UART5_IRQHandler", "UART5 global Interrupt"},
  {"TIM6_vect", "TIM6_IRQHandler", "TIM6 global Interrupt"},
  {"TIM7_vect", "TIM7_IRQHandler", "TIM7 global Interrupt"},
  {"DMA2_Channel1_vect", "DMA2_Channel1_IRQHandler", "DMA2 Channel 1 global Interrupt"},
  {"DMA2_Channel2_vect", "DMA2_Channel2_IRQHandler", "DMA2 Channel 2 global Interrupt"},
  {"DMA2_Channel3_vect", "DMA2_Channel3_IRQHandler", "DMA2 Channel 3 global Interrupt"},
  {"DMA2_Channel4_5_vect", "DMA2_Channel4_5_IRQHandler", "DMA2 Channel 4 and Channel 5 global Interrupt"},
};


vector_t stm32f10x_xl_vectors[STM32F10X_XL_IRQ_COUNT] =
{
  {"ADC1_2_vect", "ADC1_2_IRQHandler", "ADC1 and ADC2 global Interrupt"},
  {"USB_HP_CAN1_TX_vect", "USB_HP_CAN1_TX_IRQHandler", "USB Device High Priority or CAN1 TX Interrupts"},
  {"USB_LP_CAN1_RX0_vect", "USB_LP_CAN1_RX0_IRQHandler", "USB Device Low Priority or CAN1 RX0 Interrupts"},
  {"CAN1_RX1_vect", "CAN1_RX1_IRQHandler", "CAN1 RX1 Interrupt"},
  {"CAN1_SCE_vect", "CAN1_SCE_IRQHandler", "CAN1 SCE Interrupt"},
  {"EXTI9_5_vect", "EXTI9_5_IRQHandler", "External Line[9:5] Interrupts"},
  {"TIM1_BRK_TIM9_vect", "TIM1_BRK_TIM9_IRQHandler", "TIM1 Break Interrupt and TIM9 global Interrupt"},
  {"TIM1_UP_TIM10_vect", "TIM1_UP_TIM10_IRQHandler", "TIM1 Update Interrupt and TIM10 global Interrupt"},
  {"TIM1_TRG_COM_TIM11_vect", "TIM1_TRG_COM_TIM11_IRQHandler", "TIM1 Trigger and Commutation Interrupt and TIM11 global interrupt"},
  {"TIM1_CC_vect", "TIM1_CC_IRQHandler", "TIM1 Capture Compare Interrupt"},
  {"TIM2_vect", "TIM2_IRQHandler", "TIM2 global Interrupt"},
  {"TIM3_vect", "TIM3_IRQHandler", "TIM3 global Interrupt"},
  {"TIM4_vect", "TIM4_IRQHandler", "TIM4 global Interrupt"},
  {"I2C1_EV_vect", "I2C1_EV_IRQHandler", "I2C1 Event Interrupt"},
  {"I2C1_ER_vect", "I2C1_ER_IRQHandler", "I2C1 Error Interrupt"},
  {"I2C2_EV_vect", "I2C2_EV_IRQHandler", "I2C2 Event Interrupt"},
  {"I2C2_ER_vect", "I2C2_ER_IRQHandler", "I2C2 Error Interrupt"},
  {"SPI1_vect", "SPI1_IRQHandler", "SPI1 global Interrupt"},
  {"SPI2_vect", "SPI2_IRQHandler", "SPI2 global Interrupt"},
  {"USART1_vect", "USART1_IRQHandler", "USART1 global Interrupt"},
  {"USART2_vect", "USART2_IRQHandler", "USART2 global Interrupt"},
  {"USART3_vect", "USART3_IRQHandler", "USART3 global Interrupt"},
  {"EXTI15_10_vect", "EXTI15_10_IRQHandler", "External Line[15:10] Interrupts"},
  {"RTCAlarm_vect", "RTCAlarm_IRQHandler", "RTC Alarm through EXTI Line Interrupt"},
  {"USBWakeUp_vect", "USBWakeUp_IRQHandler", "USB Device WakeUp from suspend through EXTI Line Interrupt"},
  {"TIM8_BRK_TIM12_vect", "TIM8_BRK_TIM12_IRQHandler", "TIM8 Break Interrupt and TIM12 global Interrupt"},
  {"TIM8_UP_TIM13_vect", "TIM8_UP_TIM13_IRQHandler", "TIM8 Update Interrupt and TIM13 global Interrupt"},
  {"TIM8_TRG_COM_TIM14_vect", "TIM8_TRG_COM_TIM14_IRQHandler", "TIM8 Trigger and Commutation Interrupt and TIM14 global interrupt"},
  {"TIM8_CC_vect", "TIM8_CC_IRQHandler", "TIM8 Capture Compare Interrupt"},
  {"ADC3_vect", "ADC3_IRQHandler", "ADC3 global Interrupt"},
  {"FSMC_vect", "FSMC_IRQHandler", "FSMC global Interrupt"},
  {"SDIO_vect", "SDIO_IRQHandler", "SDIO global Interrupt"},
  {"TIM5_vect", "TIM5_IRQHandler", "TIM5 global Interrupt"},
  {"SPI3_vect", "SPI3_IRQHandler", "SPI3 global Interrupt"},
  {"UART4_vect", "UART4_IRQHandler", "UART4 global Interrupt"},
  {"UART5_vect", "UART5_IRQHandler", "UART5 global Interrupt"},
  {"TIM6_vect", "TIM6_IRQHandler", "TIM6 global Interrupt"},
  {"TIM7_vect", "TIM7_IRQHandler", "TIM7 global Interrupt"},
  {"DMA2_Channel1_vect", "DMA2_Channel1_IRQHandler", "DMA2 Channel 1 global Interrupt"},
  {"DMA2_Channel2_vect", "DMA2_Channel2_IRQHandler", "DMA2 Channel 2 global Interrupt"},
  {"DMA2_Channel3_vect", "DMA2_Channel3_IRQHandler", "DMA2 Channel 3 global Interrupt"},
  {"DMA2_Channel4_5_vect", "DMA2_Channel4_5_IRQHandler", "DMA2 Channel 4 and Channel 5 global Interrupt"},
};

vector_t stm32f10x_cl_vectors[STM32F10X_CL_IRQ_COUNT] =
{
  {"ADC1_2_vect", "ADC1_2Handler", "ADC1 and ADC2 global Interrupt"},
  {"CAN1_TX_vect", "CAN1_TXHandler", "USB Device High Priority or CAN1 TX Interrupts"},
  {"CAN1_RX0_vect", "CAN1_RX0Handler", "USB Device Low Priority or CAN1 RX0 Interrupts"},
  {"CAN1_RX1_vect", "CAN1_RX1Handler", "CAN1 RX1 Interrupt"},
  {"CAN1_SCE_vect", "CAN1_SCEHandler", "CAN1 SCE Interrupt"},
  {"EXTI9_5_vect", "EXTI9_5Handler", "External Line[9:5] Interrupts"},
  {"TIM1_BRK_vect", "TIM1_BRKHandler", "TIM1 Break Interrupt"},
  {"TIM1_UP_vect", "TIM1_UPHandler", "TIM1 Update Interrupt"},
  {"TIM1_TRG_COM_vect", "TIM1_TRG_COMHandler", "TIM1 Trigger and Commutation Interrupt"},
  {"TIM1_CC_vect", "TIM1_CCHandler", "TIM1 Capture Compare Interrupt"},
  {"TIM2_vect", "TIM2Handler", "TIM2 global Interrupt"},
  {"TIM3_vect", "TIM3Handler", "TIM3 global Interrupt"},
  {"TIM4_vect", "TIM4Handler", "TIM4 global Interrupt"},
  {"I2C1_EV_vect", "I2C1_EVHandler", "I2C1 Event Interrupt"},
  {"I2C1_ER_vect", "I2C1_ERHandler", "I2C1 Error Interrupt"},
  {"I2C2_EV_vect", "I2C2_EVHandler", "I2C2 Event Interrupt"},
  {"I2C2_ER_vect", "I2C2_ERHandler", "I2C2 Error Interrupt"},
  {"SPI1_vect", "SPI1Handler", "SPI1 global Interrupt"},
  {"SPI2_vect", "SPI2Handler", "SPI2 global Interrupt"},
  {"USART1_vect", "USART1Handler", "USART1 global Interrupt"},
  {"USART2_vect", "USART2Handler", "USART2 global Interrupt"},
  {"USART3_vect", "USART3Handler", "USART3 global Interrupt"},
  {"EXTI15_10_vect", "EXTI15_10Handler", "External Line[15:10] Interrupts"},
  {"RTCAlarm_vect", "RTCAlarmHandler", "RTC Alarm through EXTI Line Interrupt"},
  {"OTG_FS_WKUP_vect", "OTG_FS_WKUPHandler", "USB OTG FS WakeUp from suspend through EXTI Line Interrupt"},
  {"Reserved0",  NULL, "Reserved"},
  {"Reserved1",  NULL, "Reserved"},
  {"Reserved2",  NULL, "Reserved"},
  {"Reserved3",  NULL, "Reserved"},
  {"Reserved4",  NULL, "Reserved"},
  {"Reserved5",  NULL, "Reserved"},
  {"Reserved6",  NULL, "Reserved"},
  {"TIM5_vect", "TIM5Handler", "TIM5 global Interrupt"},
  {"SPI3_vect", "SPI3Handler", "SPI3 global Interrupt"},
  {"UART4_vect", "UART4Handler", "UART4 global Interrupt"},
  {"UART5_vect", "UART5Handler", "UART5 global Interrupt"},
  {"TIM6_vect", "TIM6Handler", "TIM6 global Interrupt"},
  {"TIM7_vect", "TIM7Handler", "TIM7 global Interrupt"},
  {"DMA2_Channel1_vect", "DMA2_Channel1Handler", "DMA2 Channel 1 global Interrupt"},
  {"DMA2_Channel2_vect", "DMA2_Channel2Handler", "DMA2 Channel 2 global Interrupt"},
  {"DMA2_Channel3_vect", "DMA2_Channel3Handler", "DMA2 Channel 3 global Interrupt"},
  {"DMA2_Channel4_vect", "DMA2_Channel4Handler", "DMA2 Channel 4 global Interrupt"},
  {"DMA2_Channel5_vect", "DMA2_Channel5Handler", "DMA2 Channel 5 global Interrupt"},
  {"ETH_vect", "ETHHandler", "Ethernet global Interrupt"},
  {"ETH_WKUP_vect", "ETH_WKUPHandler", "Ethernet Wakeup through EXTI line Interrupt"},
  {"CAN2_TX_vect", "CAN2_TXHandler", "CAN2 TX Interrupt"},
  {"CAN2_RX0_vect", "CAN2_RX0Handler", "CAN2 RX0 Interrupt"},
  {"CAN2_RX1_vect", "CAN2_RX1Handler", "CAN2 RX1 Interrupt"},
  {"CAN2_SCE_vect", "CAN2_SCEHandler", "CAN2 SCE Interrupt"},
  {"OTG_FS_vect", "OTG_FSHandler", "USB OTG FS global Interrupt"},
};

